### PR TITLE
✨  add somatic annot wf

### PR DESCRIPTION
**Pull request by dmiller15**
## Description

Importing the somatic annotation workflow from the somatic repository.
- Added suggested file for echtvar
- Cleaned up javascript, formatting, and readmes

Part of https://github.com/d3b-center/bixu-tracker/issues/2303 and https://github.com/d3b-center/bixu-tracker/issues/2304

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Strelka: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/ada8053b-02c4-4cd5-9351-979da0aa0890/#
- [x] Mutect: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/6f62095c-63e8-470a-a285-78ef59081bee
- [x] Varidct: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/8e127b9d-0ce6-4838-a41b-39c5740cc65d/#
- [x] Lancet: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/96a8862d-02ec-408c-bd3a-b0280af63ce3/#

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

### CODE REVIEW

**Review by sickler-alex — APPROVED** [review]

**Review by migbro — CHANGES_REQUESTED** [review]
Minor changes. Would be good to add to the docs the existence of `gnomad_3_1_1_FILTER`, what it is, how to use it, and make sure bix ops knows

**Comment by migbro** [comment]
Also forgot, should probably update default `retain_info` as well

**Comment by dmiller15** [comment]
@migbro Let me know if I covered everything. I don't think we can set a default value for retain info here because each caller has unique fields.

**Review by migbro — APPROVED** [review]
Sweet, looks good. One small typo change, Thanks!

**Pull request merged**
